name: Generate terminal

on:
  push:
    branches:
      - main
    paths:
      - "*.tape"
      - ".github/workflows/generate-terminal.yaml"
  workflow_dispatch:

jobs:
  vhs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Generate an animated gif of a terminal
      - uses: charmbracelet/vhs-action@v2
        with:
          path: profile.tape
        env:
          USER: Sam

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>
      - name: push profile.gif to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output-terminal
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
